### ISSUE TITLE
Constructive Feedback Log - Jasminder

### ISSUE THREAD

**Issue by ambergarcia** [G915-2-Data-Modeling-381/Midterm-Group-Project#7]
**Instructions**

Provide constructive feedback to the following members: 
- [x] Adrian
- [x] Amber
- [x] Oliver
- [x] Wade

Please provide at least one; Positive & Negative feedback or a feature to implement that you like.

Store your feedback here as a comment, and close your issue when complete.

**Comment by jaga41** [comment]
Comments to Adrian:
Good:
    •	Foreign Key in tables to UserAuthorization
    •	Different diagrams
    •	Valid values for ContactTitle, Flag Char, minor typo on “GradOutOf100” but good check, IsDeletion
    •	Expression for time string check
    •	Interesting naming convention, udt in front of each UDT. 
    •	Default values
    •	Gradations of time UDTs
Possible improvements:
    •	Expression for time string check a bit unclear to me
    •	Top level domains are missing
    •	Categorization in subdomains, like for related name or address strings

Comments to Amber:
Good:
    •	Style/theme tables
    •	Checks are general, like templates
    •	Default values
    •	Subdomains and use of camelCase
Possible improvements:
    •	Categorization in subdomains, like for related name or address strings
    •	Naming convention of defaults to know which column it applies to

Comments to Oliver:
Good:
    •	Naming convention of defaults differentiates those used for domains
    •	Use of camelCase
Possible improvements:
    •	Taxonomy of top-level domains
    •	Taxonomy of subdomains under top-level domains
    •	UDTs in those subdomains
    •	More check constraints/validation rules

Comments to Wade:
Good:
    •	Top level domains
Possible Improvements:
    •	Taxonomy of subdomains under top-level domains
    •	More defaults/check constraints
