### ISSUE TITLE
Constructive Feedback Log - Oliver

### ISSUE THREAD

**Issue by ambergarcia** [G915-2-Data-Modeling-381/Midterm-Group-Project#8]
**Instructions**

Provide constructive feedback to the following members: 
- [x] Adrian
- [x] Jasminder
- [x] Amber
- [x] Wade

Please provide at least one; Positive & Negative feedback or a feature to implement that you like.

Store your feedback here as a comment, and close your issue when complete.

**Comment by oliverVidalCs** [comment]
Adrian:

- Looks terrific I really liked the model, the SQL DDL file is there. Also, documentation allows you to see everything.

Jasminder:
-DDL script looks good I don't see any errors. Everything runs well and most importantly all the UDT is correctly inputted.

Amber:
-Wonderful model with a greenish background makes it really easy to see all the entities. The DDLs script also runs fine.

Wade:
-Everything is there and it works amazing work, I looked through the PDM and it seems to me all the UDT and constraints are there for every entity
