### ISSUE TITLE
Constructive Feedback Log - Wade

### ISSUE THREAD

**Issue by ambergarcia** [G915-2-Data-Modeling-381/Midterm-Group-Project#9]
**Instructions**

Provide constructive feedback to the following members: 
- [ ] Adrian
- [ ] Jasminder
- [ ] Oliver
- [ ] Amber

Please provide at least one; Positive & Negative feedback or a feature to implement that you like.

Store your feedback here as a comment, and close your issue when complete.

**Comment by tom11322** [comment]
Adrian
+ UserAuthorizationID as a foreign key
- Logical attributes are not named properly
- No fully qualified tables
- Missing default values in UserAuthorization

Amber
+ New domains hierarchy
- Missing views

Jas
+ Colorized tables
- Missing views
- Logical missing attributes

Oliver
+ Made new relationships
- Can improve domains reusable
- No fully qualified tables
